// @generated by candle-kernels/asd_exact_build_adapter_v2.rs -- Stage 2F production.
// One V2 table, one exact geometry selector, one public lookup API.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ExactOperation { Conv1d, Conv2d, ConvTranspose1d, ConvTranspose2d }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ExactOperationCall {
    pub op: ExactOperation,
    pub dim: u8,
    pub batch: usize,
    pub c_in: usize,
    pub c_out: usize,
    pub spatial0: usize,
    pub spatial1: usize,
    pub weight_rank: usize,
    pub weight0: usize,
    pub weight1: usize,
    pub weight2: usize,
    pub weight3: usize,
    pub groups: usize,
    pub kernel: usize,
    pub stride: usize,
    pub padding: usize,
    pub output_padding: usize,
    pub dilation: usize,
    pub dtype: &'static str,
    pub input_contiguous: bool,
    pub input_start_offset: usize,
    pub weight_contiguous: bool,
    pub weight_start_offset: usize,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ExactAsdMatch {
    pub policy_id: &'static str,
    pub decision_id: &'static str,
    pub state: &'static str,
    pub selected_backend: &'static str,
    pub implementation_id: &'static str,
    pub evidence_sha256: &'static str,
    pub min_integrated_speedup_x: Option<f64>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ExactUnprovenMatch {
    pub policy_id: &'static str,
    pub decision_id: &'static str,
    pub state: &'static str,
    pub selected_backend: &'static str,
    pub implementation_id: &'static str,
    pub proof_status: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum ExactMatch {
    Proven(ExactAsdMatch),
    Unproven(ExactUnprovenMatch),
}

#[derive(Clone, Copy)]
struct ExactDecision {
    id: &'static str,
    state: &'static str,
    backend: &'static str,
    implementation_id: &'static str,
    evidence_ref: &'static str,
    min_integrated_speedup_x: Option<f64>,
    op: ExactOperation,
    dim: u8,
    batch: usize,
    c_in: usize,
    c_out: usize,
    spatial0: usize,
    spatial1: usize,
    weight_rank: usize,
    weight0: usize,
    weight1: usize,
    weight2: usize,
    weight3: usize,
    groups: usize,
    kernel: usize,
    stride: usize,
    padding: usize,
    output_padding: usize,
    dilation: usize,
    dtype: &'static str,
}

pub const POLICY_ID: Option<&str> = __POLICY_ID__;
pub const TARGET_GPU_UUID: Option<&str> = __GPU_UUID__;
pub const VALIDATION_BUILD: bool = __VALIDATION__;
const DECISIONS: &[ExactDecision] = &[
__DECISIONS__];

fn env_truthy(name: &str) -> bool {
    matches!(
        std::env::var(name).ok().as_deref(),
        Some("1") | Some("true") | Some("yes") | Some("on")
    )
}

fn exact_geometry(d: &ExactDecision, call: ExactOperationCall) -> bool {
    d.op == call.op
        && d.dim == call.dim
        && d.batch == call.batch
        && d.c_in == call.c_in
        && d.c_out == call.c_out
        && d.spatial0 == call.spatial0
        && d.spatial1 == call.spatial1
        && d.weight_rank == call.weight_rank
        && d.weight0 == call.weight0
        && d.weight1 == call.weight1
        && d.weight2 == call.weight2
        && d.weight3 == call.weight3
        && d.groups == call.groups
        && d.kernel == call.kernel
        && d.stride == call.stride
        && d.padding == call.padding
        && d.output_padding == call.output_padding
        && d.dilation == call.dilation
        && d.dtype == call.dtype
}

// The only exact geometry selector. Status/proof/opt-in checks happen after it.
fn find_exact(call: ExactOperationCall) -> Option<&'static ExactDecision> {
    if env_truthy("CANDLE_ASD_EXACT_DISABLE")
        || !call.input_contiguous
        || call.input_start_offset != 0
        || !call.weight_contiguous
        || call.weight_start_offset != 0
    {
        return None;
    }
    DECISIONS.iter().find(|d| exact_geometry(d, call))
}

fn device_scope_ok(actual_uuid: Option<&str>) -> bool {
    TARGET_GPU_UUID.is_some() && actual_uuid == TARGET_GPU_UUID
}

fn proven(d: &'static ExactDecision) -> Option<ExactAsdMatch> {
    if d.backend != "raw_cuda" || d.evidence_ref == "unresolved" {
        return None;
    }
    match (d.state, d.implementation_id) {
        ("promoted", "candle.grouped-transpose.raw.v1") => {
            if !env_truthy("CANDLE_ASD_V2_CT1D_ENABLE") {
                return None;
            }
        }
        ("promoted", "candle.depthwise-conv2d-5x5.raw.v1") => {
            // Stage 2F closes the historical real-dispatch evidence for these four
            // exact points. Production lookup requires only the exact device scope.
        }
        ("promoted", implementation_id) if implementation_id.starts_with("candle.sm61-exact-grouped.") => {
            // Stage 2E evidence binding promotes these exact rows. No positive opt-in
            // remains; the explicit kill-switch is retained for operational rollback.
            if env_truthy("CANDLE_SM61_EXACT_GROUPED_DISABLE") {
                return None;
            }
        }
        _ => return None,
    }
    Some(ExactAsdMatch {
        policy_id: POLICY_ID?,
        decision_id: d.id,
        state: d.state,
        selected_backend: d.backend,
        implementation_id: d.implementation_id,
        evidence_sha256: d.evidence_ref,
        min_integrated_speedup_x: d.min_integrated_speedup_x,
    })
}

fn unproven(d: &'static ExactDecision) -> Option<ExactUnprovenMatch> {
    if d.state != "validation_only_unproven"
        || d.backend != "raw_cuda"
        || !d.implementation_id.starts_with("candle.sm61-exact-grouped.")
        || d.evidence_ref != "unresolved"
        || d.min_integrated_speedup_x.is_some()
        || !env_truthy("CANDLE_ASD_SM61_EXACT_GROUPED_ENABLE")
        || env_truthy("CANDLE_SM61_EXACT_GROUPED_DISABLE")
    {
        return None;
    }
    Some(ExactUnprovenMatch {
        policy_id: POLICY_ID?,
        decision_id: d.id,
        state: d.state,
        selected_backend: d.backend,
        implementation_id: d.implementation_id,
        proof_status: "unresolved",
    })
}

// Stage 2F: the sole public production policy lookup.
pub fn lookup(call: ExactOperationCall, actual_uuid: Option<&str>) -> Option<ExactMatch> {
    if !device_scope_ok(actual_uuid) {
        return None;
    }
    let d = find_exact(call)?;
    if let Some(m) = proven(d) {
        return Some(ExactMatch::Proven(m));
    }
    unproven(d).map(ExactMatch::Unproven)
}
