//! @generated by flow-adaptive-tuner v0.3.26.
//! Production-style exact grouped dispatch validated on one device-scoped SM61 evidence target.
//! Unknown or non-matching devices always fall through to the existing Candle dispatch.

use crate::backend::BackendStorage;
use crate::cuda_backend::{CudaStorage, CudaStorageSlice as S, WrapErr};
use crate::{DType, Layout, Result};
use cudarc::driver::{LaunchConfig, PushKernelArg};

use super::{ParamsConv1D, ParamsConvTranspose1D, ParamsConvTranspose2D};

#[derive(Clone, Copy, Debug)]
struct ExactDecision {
    geometry_id: &'static str,
    candidate_id: &'static str,
    entry: &'static str,
    family: &'static str,
    dim: u8,
    batch: usize,
    c_in: usize,
    c_out: usize,
    s0: usize,
    s1: usize,
    kernel: usize,
    stride: usize,
    dilation: usize,
    padding: usize,
    output_padding: usize,
    groups: usize,
    output_count: usize,
    grid_x: u32,
    block_x: u32,
}

const DECISIONS: &[ExactDecision] = &[
    ExactDecision {
        geometry_id: "ct1d-s32-g2",
        candidate_id: "ct1d-s32-g2-u1-b256",
        entry: "flow_v0322_ct1d_s32_g2_u1_b256",
        family: "conv_transpose",
        dim: 1,
        batch: 1,
        c_in: 128,
        c_out: 128,
        s0: 32,
        s1: 1,
        kernel: 3,
        stride: 2,
        dilation: 1,
        padding: 1,
        output_padding: 1,
        groups: 2,
        output_count: 8192,
        grid_x: 32,
        block_x: 256,
    },
    ExactDecision {
        geometry_id: "ct1d-s32-g4",
        candidate_id: "ct1d-s32-g4-u1-b256",
        entry: "flow_v0322_ct1d_s32_g4_u1_b256",
        family: "conv_transpose",
        dim: 1,
        batch: 1,
        c_in: 128,
        c_out: 128,
        s0: 32,
        s1: 1,
        kernel: 3,
        stride: 2,
        dilation: 1,
        padding: 1,
        output_padding: 1,
        groups: 4,
        output_count: 8192,
        grid_x: 32,
        block_x: 256,
    },
    ExactDecision {
        geometry_id: "ct1d-s32-g8",
        candidate_id: "ct1d-s32-g8-u1-b256",
        entry: "flow_v0322_ct1d_s32_g8_u1_b256",
        family: "conv_transpose",
        dim: 1,
        batch: 1,
        c_in: 128,
        c_out: 128,
        s0: 32,
        s1: 1,
        kernel: 3,
        stride: 2,
        dilation: 1,
        padding: 1,
        output_padding: 1,
        groups: 8,
        output_count: 8192,
        grid_x: 32,
        block_x: 256,
    },
    ExactDecision {
        geometry_id: "ct1d-s32-g16",
        candidate_id: "ct1d-s32-g16-u1-b256",
        entry: "flow_v0322_ct1d_s32_g16_u1_b256",
        family: "conv_transpose",
        dim: 1,
        batch: 1,
        c_in: 128,
        c_out: 128,
        s0: 32,
        s1: 1,
        kernel: 3,
        stride: 2,
        dilation: 1,
        padding: 1,
        output_padding: 1,
        groups: 16,
        output_count: 8192,
        grid_x: 32,
        block_x: 256,
    },
    ExactDecision {
        geometry_id: "ct2d-s32-g16",
        candidate_id: "ct2d-s32-g16-u4-b128",
        entry: "flow_v0322_ct2d_s32_g16_u4_b128",
        family: "conv_transpose",
        dim: 2,
        batch: 1,
        c_in: 128,
        c_out: 128,
        s0: 32,
        s1: 32,
        kernel: 3,
        stride: 2,
        dilation: 1,
        padding: 1,
        output_padding: 1,
        groups: 16,
        output_count: 524288,
        grid_x: 4096,
        block_x: 128,
    },
    ExactDecision {
        geometry_id: "ct2d-s32-g32",
        candidate_id: "ct2d-s32-g32-u4-b64",
        entry: "flow_v0322_ct2d_s32_g32_u4_b64",
        family: "conv_transpose",
        dim: 2,
        batch: 1,
        c_in: 128,
        c_out: 128,
        s0: 32,
        s1: 32,
        kernel: 3,
        stride: 2,
        dilation: 1,
        padding: 1,
        output_padding: 1,
        groups: 32,
        output_count: 524288,
        grid_x: 8192,
        block_x: 64,
    },
    ExactDecision {
        geometry_id: "gc1d-l128-g8",
        candidate_id: "gc1d-l128-g8-u1-b256",
        entry: "flow_v0322_gc1d_l128_g8_u1_b256",
        family: "conv",
        dim: 1,
        batch: 1,
        c_in: 64,
        c_out: 64,
        s0: 128,
        s1: 1,
        kernel: 3,
        stride: 1,
        dilation: 1,
        padding: 1,
        output_padding: 0,
        groups: 8,
        output_count: 8192,
        grid_x: 32,
        block_x: 256,
    },
];

fn env_truthy(name: &str) -> bool {
    matches!(
        std::env::var(name).ok().as_deref(),
        Some("1") | Some("true") | Some("yes") | Some("on")
    )
}

fn scope_matches() -> bool {
    if candle_kernels::CUDA_BUILD_COMPUTE_CAP != 61 {
        return false;
    }
    let Some(expected) = candle_kernels::sm61_exact_grouped_scope::EVIDENCE_GPU_UUID else {
        return false;
    };
    std::env::var("CANDLE_ASD_TARGET_GPU_UUID").ok().as_deref() == Some(expected)
}

fn enabled() -> bool {
    scope_matches() && !env_truthy("CANDLE_SM61_EXACT_GROUPED_DISABLE")
}

fn trace_enabled() -> bool {
    env_truthy("CANDLE_SM61_EXACT_GROUPED_TRACE")
}

fn layout_ok(l: &Layout) -> bool {
    l.is_contiguous() && l.start_offset() == 0
}

fn exact_call_eligible(
    input: &CudaStorage,
    input_l: &Layout,
    kernel: &CudaStorage,
    kernel_l: &Layout,
) -> bool {
    input.dtype() == DType::F32
        && kernel.dtype() == DType::F32
        && layout_ok(input_l)
        && layout_ok(kernel_l)
        && input.device.id() == kernel.device.id()
}

fn find_conv1d(p: &ParamsConv1D) -> Option<&'static ExactDecision> {
    DECISIONS.iter().find(|d| {
        d.family == "conv"
            && d.dim == 1
            && d.batch == p.b_size
            && d.c_in == p.c_in
            && d.c_out == p.c_out
            && d.s0 == p.l_in
            && d.kernel == p.k_size
            && d.stride == p.stride
            && d.dilation == p.dilation
            && d.padding == p.padding
            && d.output_padding == 0
            && d.groups == p.groups
    })
}

fn find_ct1d(p: &ParamsConvTranspose1D) -> Option<&'static ExactDecision> {
    DECISIONS.iter().find(|d| {
        d.family == "conv_transpose"
            && d.dim == 1
            && d.batch == p.b_size
            && d.c_in == p.c_in
            && d.c_out == p.c_out
            && d.s0 == p.l_in
            && d.kernel == p.k_size
            && d.stride == p.stride
            && d.dilation == p.dilation
            && d.padding == p.padding
            && d.output_padding == p.output_padding
            && d.groups == p.groups
    })
}

fn find_ct2d(p: &ParamsConvTranspose2D) -> Option<&'static ExactDecision> {
    DECISIONS.iter().find(|d| {
        d.family == "conv_transpose"
            && d.dim == 2
            && d.batch == p.b_size
            && d.c_in == p.c_in
            && d.c_out == p.c_out
            && d.s0 == p.i_h
            && d.s1 == p.i_w
            && d.kernel == p.k_h
            && p.k_h == p.k_w
            && d.stride == p.stride
            && d.dilation == p.dilation
            && d.padding == p.padding
            && d.output_padding == p.output_padding
            && d.groups == p.groups
    })
}

fn launch_exact(
    decision: &'static ExactDecision,
    input: &CudaStorage,
    kernel: &CudaStorage,
) -> Result<CudaStorage> {
    let ptx = candle_kernels::sm61_exact_grouped_ptx(decision.candidate_id).ok_or_else(|| {
        crate::Error::Msg(format!(
            "missing SM61 exact-grouped PTX for {}",
            decision.candidate_id
        ))
    })?;
    let dev = input.device.clone();
    let func = dev.get_or_load_custom_func(decision.entry, decision.candidate_id, ptx)?;
    let out = unsafe { dev.alloc::<f32>(decision.output_count)? };
    let cfg = LaunchConfig {
        grid_dim: (decision.grid_x, 1, 1),
        block_dim: (decision.block_x, 1, 1),
        shared_mem_bytes: 0,
    };
    let slice = match (&input.slice, &kernel.slice) {
        (S::F32(x), S::F32(w)) => {
            let mut builder = func.builder();
            builder.arg(x).arg(w).arg(&out);
            unsafe { builder.launch(cfg) }.w()?;
            S::F32(out)
        }
        _ => crate::bail!("SM61 exact-grouped internal storage dtype mismatch"),
    };
    if trace_enabled() {
        eprintln!(
            "[candle sm61 exact-grouped] geometry={} candidate={} entry={} scope=device submitted_backend=raw_exact",
            decision.geometry_id, decision.candidate_id, decision.entry,
        );
    }
    Ok(CudaStorage { slice, device: dev })
}

pub(super) fn try_launch_conv1d(
    input: &CudaStorage,
    input_l: &Layout,
    kernel: &CudaStorage,
    kernel_l: &Layout,
    p: &ParamsConv1D,
) -> Result<Option<CudaStorage>> {
    if !enabled() || !exact_call_eligible(input, input_l, kernel, kernel_l) {
        return Ok(None);
    }
    let Some(d) = find_conv1d(p) else {
        return Ok(None);
    };
    Ok(Some(launch_exact(d, input, kernel)?))
}

pub(super) fn try_launch_ct1d(
    input: &CudaStorage,
    input_l: &Layout,
    kernel: &CudaStorage,
    kernel_l: &Layout,
    p: &ParamsConvTranspose1D,
) -> Result<Option<CudaStorage>> {
    if !enabled() || !exact_call_eligible(input, input_l, kernel, kernel_l) {
        return Ok(None);
    }
    let Some(d) = find_ct1d(p) else {
        return Ok(None);
    };
    Ok(Some(launch_exact(d, input, kernel)?))
}

pub(super) fn try_launch_ct2d(
    input: &CudaStorage,
    input_l: &Layout,
    kernel: &CudaStorage,
    kernel_l: &Layout,
    p: &ParamsConvTranspose2D,
) -> Result<Option<CudaStorage>> {
    if !enabled() || !exact_call_eligible(input, input_l, kernel, kernel_l) {
        return Ok(None);
    }
    let Some(d) = find_ct2d(p) else {
        return Ok(None);
    };
    Ok(Some(launch_exact(d, input, kernel)?))
}
